<?php

namespace App\Models;

use App\Models\Concerns\HasAutoGeneratedSlug;
use App\Models\Concerns\HasPracticeUsage;
use App\Models\Concerns\HasTranslatedTitle;
use Database\Factories\ExperienceLevelFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property int $id
 * @property array<string, string> $title
 * @property string $slug
 * @property-read int|null $practices_count
 */
class ExperienceLevel extends Model
{
    use HasAutoGeneratedSlug;

    /** @use HasFactory<ExperienceLevelFactory> */
    use HasFactory;

    use HasPracticeUsage;
    use HasTranslatedTitle;

    protected $fillable = [
        'title',
        'slug',
    ];

    /**
     * @return HasMany<Practice, $this>
     */
    public function practices(): HasMany
    {
        return $this->hasMany(Practice::class);
    }
}
