<?php

namespace App\Models;

use App\Models\Concerns\HasAutoGeneratedSlug;
use App\Models\Concerns\HasTranslatedTitle;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class FocusProblem extends Model
{
    use HasAutoGeneratedSlug;
    use HasFactory;
    use HasTranslatedTitle;

    protected $fillable = [
        'title',
        'slug',
    ];

    public function practices(): HasMany
    {
        return $this->hasMany(Practice::class);
    }
}
