<?php

namespace App\Models\Concerns;

use Illuminate\Support\Str;

trait HasAutoGeneratedSlug
{
    protected static function bootHasAutoGeneratedSlug(): void
    {
        static::saving(function ($model): void {
            if ($model->isDirty('title') || blank($model->slug)) {
                $model->slug = $model->generateUniqueSlug();
            }
        });
    }

    protected function initializeHasAutoGeneratedSlug(): void
    {
        $this->hidden = array_values(array_unique([
            ...$this->hidden,
            'slug',
        ]));
    }

    public function generateUniqueSlug(): string
    {
        $baseSlug = $this->baseSlug();
        $slug = $baseSlug;
        $suffix = 2;

        while ($this->newQuery()
            ->where('slug', $slug)
            ->when($this->exists, fn ($query) => $query->whereKeyNot($this->getKey()))
            ->exists()) {
            $slug = "{$baseSlug}-{$suffix}";
            $suffix++;
        }

        return $slug;
    }

    protected function baseSlug(): string
    {
        $titles = is_array($this->title) ? $this->title : [];
        $fallbackLocale = config('app.fallback_locale', 'en');
        $sourceTitle = trim((string) ($titles[$fallbackLocale] ?? ''));

        if ($sourceTitle === '') {
            $sourceTitle = collect($titles)
                ->map(fn ($title): string => trim((string) $title))
                ->first(fn (string $title): bool => $title !== '')
                ?? class_basename($this);
        }

        return Str::slug($sourceTitle) ?: 'item';
    }
}
