<?php

namespace App\Models\Concerns;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * @phpstan-require-extends Model
 */
trait HasAutoGeneratedSlug
{
    protected static function bootHasAutoGeneratedSlug(): void
    {
        static::saving(function (self $model): void {
            if ($model->isDirty('title') || blank($model->getAttribute('slug'))) {
                $model->setAttribute('slug', $model->generateUniqueSlug());
            }
        });
    }

    protected function initializeHasAutoGeneratedSlug(): void
    {
        $this->hidden = array_values(array_unique([
            ...$this->hidden,
            'slug',
        ]));
    }

    public function generateUniqueSlug(): string
    {
        $baseSlug = $this->baseSlug();
        $slug = $baseSlug;
        $suffix = 2;

        while ($this->newQuery()
            ->where('slug', $slug)
            ->when($this->exists, fn ($query) => $query->whereKeyNot($this->getKey()))
            ->exists()) {
            $slug = "{$baseSlug}-{$suffix}";
            $suffix++;
        }

        return $slug;
    }

    protected function baseSlug(): string
    {
        $titleAttribute = $this->getAttribute('title');
        $titles = is_array($titleAttribute) ? $titleAttribute : [];
        $fallbackLocale = config('app.fallback_locale', 'en');
        $fallbackLocale = is_string($fallbackLocale) ? $fallbackLocale : 'en';
        $fallbackTitle = $titles[$fallbackLocale] ?? '';
        $sourceTitle = is_string($fallbackTitle) ? trim($fallbackTitle) : '';

        if ($sourceTitle === '') {
            foreach ($titles as $title) {
                if (! is_string($title)) {
                    continue;
                }

                $sourceTitle = trim($title);

                if ($sourceTitle !== '') {
                    break;
                }
            }
        }

        if ($sourceTitle === '') {
            $sourceTitle = class_basename($this);
        }

        $slug = Str::slug($sourceTitle);

        return $slug !== '' ? $slug : 'item';
    }
}
